services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/ -b 0.0.0.0
    depends_on:
      db-emprunts: 
        condition: service_started
      rabbitmq :
        condition: service_healthy
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db-emprunts
    ports:
      - "5555:5555"
    networks:
      - app_network


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-emprunts'
    environment:
      RABBITMQ_DEFAULT_USER: admin 
      RABBITMQ_DEFAULT_PASS: admin 
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - app_network

  db-emprunts:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./migrations/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres-db:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres-db:
  rabbitmq-data:
  rabbitmq-log:


networks:
  app_network:
    external: true