services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-emprunts'
    environment:
      RABBITMQ_DEFAULT_USER: admin 
      RABBITMQ_DEFAULT_PASS: admin 
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
  api:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
  rabbitmq-data:
  rabbitmq-log:
